# Generated by Django 6.0.4 on 2026-04-21 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_players', to='team.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('to_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_players', to='team.team')),
            ],
        ),
    ]
