# Generated by Django 6.0.4 on 2026-05-05 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('players', '0004_alter_player_team'),
        ('team', '0004_alter_teamplayer_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('listing_type', models.CharField(choices=[('system', 'Sistema'), ('user', 'Usuario')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_listings', to='players.player')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selling_listings', to='team.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
