# Generated by Django 6.0.4 on 2026-04-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='red_cards',
        ),
        migrations.RemoveField(
            model_name='player',
            name='yellow_cards',
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('LES', 'Lesionado'), ('DIS', 'Disponible'), ('DUD', 'Dudoso'), ('NOD', 'No disponible')], default='DIS', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('MED', 'Centrocampista'), ('DEL', 'Delantero')], max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='price',
            field=models.FloatField(default=10000000),
        ),
    ]
