# Generated by Django 6.0.4 on 2026-04-28 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_assists_remove_player_goals_and_more'),
        ('team', '0003_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, default='Agentes Libres', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FutPlayers', to='team.team'),
        ),
    ]
