# Generated by Django 6.0.4 on 2026-05-05 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_team'),
        ('team', '0003_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FutPlayers', to='team.team'),
        ),
    ]
