# Generated by Django 6.0.4 on 2026-04-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='El Pepe', max_length=36),
        ),
    ]
