# Generated by Django 6.0.4 on 2026-04-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
