# Generated by Django 6.0.4 on 2026-05-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_player_team'),
        ('team', '0003_alter_team_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamplayer',
            unique_together={('team', 'player')},
        ),
    ]
