# Generated by Django 6.0.4 on 2026-05-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchdays', '0002_rename_points_playermatchdaystats_against_goals_and_more'),
        ('players', '0004_alter_player_team'),
        ('team', '0004_alter_teamplayer_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_lineups', to='players.player')),
                ('matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchdays.matchday')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
            options={
                'unique_together': {('team', 'matchday')},
            },
        ),
        migrations.CreateModel(
            name='LineupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starter', models.BooleanField(default=True)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.lineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
            options={
                'unique_together': {('lineup', 'player')},
            },
        ),
    ]
