# Generated by Django 6.0.4 on 2026-04-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchdays', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermatchdaystats',
            old_name='points',
            new_name='against_goals',
        ),
        migrations.AddField(
            model_name='playermatchdaystats',
            name='MVP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playermatchdaystats',
            name='bonus_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchdaystats',
            name='clearences',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchdaystats',
            name='final_result',
            field=models.CharField(choices=[('win', 'Victoria'), ('draw', 'Empate'), ('loss', 'Derrota')], default='draw', max_length=4),
        ),
        migrations.AddField(
            model_name='playermatchdaystats',
            name='key_passes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchdaystats',
            name='lost_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchdaystats',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
